server:
  port: 8080

spring:
  application:
    name: beaver-backend

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}