server:
  port: 8080

spring:
  application:
    name: beaver-budget-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/beaver_budget_db
    username: beaver_user
    password: beaver_pass
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: beaver_budget
    create-schemas: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: TRACE
    org.springframework.jdbc.datasource: DEBUG
